language: node_js
node_js:
- '8'
before_script:
- npm install -g --silent @angular/cli
script:
  - chmod +x build.sh
  - ./build.sh
  - chmod +x dist
  - chmod +x dist/equimosis-web
# blocklist
branches:
  except:
  - development
# safelist	
branches:	
  only:	
  - master
before_deploy:
- ls
- ls dist
- ls dist/equimosis-web
- sudo cp manifest.yml dist/equimosis-web
- sudo cp Staticfile dist/equimosis-web
- ls dist/equimosis-web
- cd dist/equimosis-web
deploy:
  - provider: cloudfoundry
    skip_cleanup: true
    username: 
      secure: "YZbUgkuNy2k9mdC/QJ+Vwg+G+MsU363V3dqQ/HmdBZ/b20qppoxaAJwwzOM9kyD2zE/N/7jRsnwxkV2o9wF7oDUfTDhihDMULL6gJLTGuFbh/RQlQSpE4i6ZRFgcVFR1MANtmlY3UJkFsE3PMPFQzGhXijyGDQI+9MqCgGwPXPh7ZduWmvYKlr1eUcDNvYHeZMUvDEflIrwhZ6gPzLkczcLQ4s0fkvBsQaxnf3HJ5Yqap7t4i6Xk86iyrIeMiw42u5kCi+kWYiWeY3yGjMzgiE0ZloQUYSop8GW3Hwfz5vaQv+LGYlFYgsWnQwob4W4e4M3Qnt9SDMjksJZUfwaFNgrU0ly7+8B7pDIzTFgvtGJ+t/mCi5y9PhHi3aEYAyDHhwhFvGtX9PyIlMG6yiRHxsVeC9QygCVHi45uj1Q9Q/B+f/skeWRjrdO5wZ7YJL1EopvjlN+DTSnGrcxMNknYE0kIz3mPySIB8N3H8j1nBz8U1qpWJk4ccT1VNhoV6VIhLU+veg9kz82snqfTvrGiAFEgrf7H/zlLmXlpcMfzDCf43RTE/79KB5d1+WMdmADOLywAopcCjnWOnDAaAeEzbBc63MFg6ZHjd8XrUG1efqSpg3jwBUrZoa00AGHJd7AFCcxcrR99371U5dUbER4bL9qQwlOZ6/2HpoGSFRDPbZE="
    password: 
      secure: "PXQFmVD0egEm0s8oF6m/FQslz4vj/eWNSM8Z2MglfPceEEPl4Y+raZHK6qIEkhFTPCk3FK1a6PXAz83XDs5JdO0LFX/zqQiOfdhGSka7X7mv7aLSNuQHx4alVYOQ96x352neXk8whV5J4M6kar2nRRcUQkmNyp3RxCtPDO9Vno7ONtbiR6zAhJV6WUWykOQZTf/PnJds51CwdGT0IT1KLfUJ742roEbqk4/mHz2wM+YUok32wN92ss1G/JHfakV6gHThYgNhmF4kR/8kyFF+R+lz2OPrXlh8EA+AE0CKACM04flyST46xEEGWVnF2aUPVh1Xmobsvd/AzEBYDL9JHDRRbTsEZkFGEw7/9tfdt4ITG1HEOq9YDmpKjyFvxjpazVrdJ+C1j5+LUier+uxX2CLDCWW7bRDYTfJoDqQa/HFKMYyNGqyTbLFnjABJa1YH3/Mv2cyEuA1v+ZhfHY3urVlyhXjirW87SHwinJvtgJnEBsWzCo3R7U90nLfWrwlTRqU/Xsw5PwsDtk+kbabKQfmi5H975Pvv/NshbDVJwPSnm+ljQkXtoH8meTBjpcnbW+EHGj1gz7NEHhpEg3k9yzNNCV1NXThHUWItFgW8jkkm+3Y1FBXG3bzyPusQ06wJ03hv4rVjsSW43YVgd19N+pxt853Wl2X3MYAqxjx28IA="
    api: https://api.run.pivotal.io
    organization: 
      secure: "doNHp5KdDzVKoqnQv8tv3MI/7mEaQLx+Eaxc8OIgnpbP0xqBvPOaZHhNwYccQol6lsm3PmjTetEoKFIaZS4cpRaPGly/sxoitPPzovsa56dkktrhOGY4VnQE1BKq8rDkUTevbPjhAx8aAQa5oTT2YVO0sOczpSovti2rOcUfw/cpB1gnlkbQFSl6+HdQRtZPbktE0dttNZeqcbVPIwfm9MvH6LdcufjSOo5lUm23CEDU4KYoKPdfGroYQimJ0noZIZ241aXrE9C4zV+rAgyhvk6dGXFpntjYRetVds1A2kIb3Lpl5R2Sq+GaQrP5/+cdpzHsFTcT1QywEqz46g/gI6dYL9YZKL93HfZ8oeFa47lZNWcCo6cvyR7LlX4R/rjRnlL4cHgjBKdJzumJYxKaoiZAESw5xb2b9gRRYo3sXIXVUEk6sRwtYZVCOiZ/ZICsDrtDtOeIdB5Urot/tIVHIlMoInZQo/BLmd1Jn17fbILBIbmsI+lIoPDpzwnjANPDigves7t7lEMnfV4v7NOBfXHI3h886to8sMHh00FPtPJW7WzlMbnppspAZ6XjMR5Blh/DnN54k1+JmylFMt4rC4ZPe0f0UpcE6r767S5W+53CFhXBnUcqffJV3bwvkJc8odLsAmGcmVMQWyrCdNqhaZ+umWyWn1/d53/JA0MxVrw="
    space: development
    on:
        branch: master
notifications:
  email:
    on_failure: change
    on_success: change
