language: node_js
node_js:
- '8'
before_script:
- npm install -g --silent @angular/cli
script:
  - chmod +x build.sh
  - ./build.sh
  - chmod +x dist
  - chmod +x dist/equimosis-web
# blocklist
branches:
  except:
  - development
# safelist	
branches:	
  only:	
  - master
before_deploy:
- ls
- ls dist
- ls dist/equimosis-web
- sudo cp manifest.yml dist/equimosis-web
- sudo cp Staticfile dist/equimosis-web
- ls dist/equimosis-web
- cd dist/equimosis-web
deploy:
  - provider: cloudfoundry
    skip_cleanup: true
    username: richar.fernandez@unmsm.edu.pe
    password: ric.fevil.Pivotal.123
    api: https://api.run.pivotal.io
    organization: rfernandezvilchez
    space: development
notifications:
  email:
    on_failure: change
    on_success: change
